#Any time we use docker we need superuser permissions
sudo: required

# Added docker in services , so travise understands we need docker cli pre installed
services:
  - docker

# Series of steps to run before our tests
before_install:
  - docker build -t raghav/docker-react -f Dockerfile.dev .

#All the command needs to be excuted when our tests actually ran just like before_install
script:
#The CI=true environmental variable should allow to exit after the tests have been run so there's no need to the coverage flag
  - docker run -e CI=true raghav/docker-react npm run test

deploy:
# Deploy code to aws
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-059683320537"
    bucket_path: "docker-react"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY